import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { encodePacket, randomId, toHex, withRelayHop } from "./codec.js";
import { generateIdentity } from "./crypto.js";
import { encodeStatus } from "./payload.js";

const here = dirname(fileURLToPath(import.meta.url));

export function buildFixtureObject(now = 1_700_000_000_000) {
  const id = generateIdentity();
  const messageId = randomId(16);
  const origin = randomId(16);
  const incident = randomId(16);
  const nonce = randomId(12);
  const payload = encodeStatus({
    t: "flood",
    s: "need_help",
    n: 3,
    inj: "moderate",
    mob: "assisted",
    vul: 1,
    txt: "water rising",
    lang: "en",
    vl: "eyewitness",
  });
  const raw = encodePacket(
    {
      priority: 1,
      payloadType: "status",
      messageId,
      originPseudonym: origin,
      incidentId: incident,
      eventTimestampMs: now,
      expiryTimestampMs: now + 60 * 60 * 1000,
      nonce,
      sequence: 1,
      payload,
      location: { latE7: 186_298_000, lonE7: 737_997_000, accuracyM: 12, ageSec: 3 },
      simulated: true,
      hopLimit: 5,
    },
    id,
  );
  const relayed = withRelayHop(raw);
  if (!relayed.ok) throw new Error(relayed.error);
  const tampered = raw.slice();
  tampered[tampered.length - 70] ^= 0x01;
  return {
    description: "DMSP/1 vectors generated by shared-protocol. Kotlin codec must match. simulated=true.",
    now,
    publicKeyHex: toHex(id.publicKeyRaw),
    privateKeyPem: id.privateKeyPem,
    validHex: toHex(raw),
    relayedHex: toHex(relayed.bytes),
    tamperedHex: toHex(tampered),
    messageIdHex: toHex(messageId),
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const out = resolve(here, "../fixtures/vectors.json");
  mkdirSync(dirname(out), { recursive: true });
  const fixture = buildFixtureObject();
  writeFileSync(out, JSON.stringify(fixture, null, 2));
  console.log(`wrote ${out}`);
}
