import { FormEvent, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api, setToken, type Incident, type Summary } from "./api";
import { Bars, Confirm, Empty, ErrorNote, Skeleton, StateChip, useApi } from "./ui";
import { FieldMap, age, stale } from "./mapview";

export function LoginPage() {
  const navigate = useNavigate();
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    setPending(true);
    setError(null);
    try {
      const res = await api<{ token: string }>("/api/v1/auth/login", {
        method: "POST",
        body: JSON.stringify({ email: data.get("email"), password: data.get("password") }),
      });
      setToken(res.token);
      navigate("/");
    } catch (err) {
      setError(err instanceof Error ? err.message : "login failed");
    } finally {
      setPending(false);
    }
  }
  return (
    <div className="min-h-screen grid md:grid-cols-2">
      <section className="p-8 bg-[#1a1713] border-r border-line">
        <p className="tracking-[0.18em] text-hi font-bold">DISASTERMESH</p>
        <h1 className="text-5xl leading-none mt-4 mb-4">Command desk</h1>
        <p className="text-mute max-w-md">Operators see stored reports, not a promise that anyone has been rescued. Source authentication is not factual verification. Official warnings are never generated by the assistant.</p>
      </section>
      <section className="p-8">
        <h2>Operator sign in</h2>
        <form className="grid gap-3 max-w-md" onSubmit={onSubmit}>
          <label>Email<input name="email" type="email" autoComplete="username" required /></label>
          <label>Password<input name="password" type="password" autoComplete="current-password" required /></label>
          <ErrorNote error={error} />
          <button className="btn primary" disabled={pending}>{pending ? "Checking…" : "Enter desk"}</button>
        </form>
      </section>
    </div>
  );
}

export function OverviewPage() {
  const { data, error, loading } = useApi<Summary>("/api/v1/dashboard/summary");
  return (
    <section>
      <h1 className="mt-0">Overview</h1>
      <p className="text-mute">Live records only. Simulator counts stay on the simulator page.</p>
      <ErrorNote error={error} />
      {loading && <Skeleton rows={4} />}
      {data && (
        <>
          <div className="grid-stats">
            <Stat label="Stated people" value={data.counts.statedPeople} note="Sum of counts people reported. Not a census." />
            <Stat label="Need help" value={data.counts.needHelp} />
            <Stat label="Self-reported safe" value={data.counts.safe} note="Not proof of safety." />
            <Stat label="Evacuating" value={data.counts.evacuating} />
            <Stat label="Unknown" value={data.counts.unknown} note="Silence is unknown, never safe." />
            <Stat label="Active incidents" value={data.activeIncidents} />
            <Stat label="Groups" value={data.groups} />
            <Stat label="Teams" value={data.teams} />
          </div>
          <p className="text-mute">Last sync: {data.lastSyncAt ? new Date(Number(data.lastSyncAt)).toISOString() : "never"} · {data.disclaimer}</p>
        </>
      )}
    </section>
  );
}

function Stat({ label, value, note }: { label: string; value: number; note?: string }) {
  return <article className="card"><span className="text-mute text-sm">{label}</span><b>{value}</b>{note && <small className="text-mute">{note}</small>}</article>;
}

export function MapPage() {
  const { data, error, loading } = useApi<{ incidents: Incident[] }>("/api/v1/incidents");
  return (
    <section>
      <h1 className="mt-0">Incident map</h1>
      <p className="text-mute">Circles are accuracy, not certainty. Stale reports stay visible and are marked.</p>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && <FieldMap incidents={data.incidents} />}
      {data && (
        <ul>
          {data.incidents.filter((i) => stale(i.event_timestamp)).map((i) => (
            <li key={i.id}>Stale: {i.id} · {age(i.event_timestamp)} · {i.emergency_state}</li>
          ))}
        </ul>
      )}
    </section>
  );
}

export function InboxPage() {
  const [q, setQ] = useState("");
  const [state, setState] = useState("");
  const [urgency, setUrgency] = useState("");
  const [verification, setVerification] = useState("");
  const [assigned, setAssigned] = useState("");
  const [sort, setSort] = useState("priority");
  const query = new URLSearchParams({ q, state, urgency, verification, assigned }).toString();
  const { data, error, loading, reload } = useApi<{ incidents: Incident[] }>(`/api/v1/incidents?${query}`);
  const [ackId, setAckId] = useState<string | null>(null);
  const rows = useMemo(() => {
    const list = [...(data?.incidents ?? [])];
    list.sort((a, b) => sort === "age" ? Number(b.event_timestamp) - Number(a.event_timestamp) : a.priority - b.priority);
    return list;
  }, [data, sort]);
  return (
    <section>
      <h1 className="mt-0">Incident inbox</h1>
      <div className="grid md:grid-cols-6 gap-2 mb-4">
        <input aria-label="Search" placeholder="Search" value={q} onChange={(e) => setQ(e.target.value)} />
        <select aria-label="State" value={state} onChange={(e) => setState(e.target.value)}><option value="">Any state</option><option value="need_help">Need help</option><option value="safe">Safe</option><option value="evacuating">Evacuating</option><option value="unknown">Unknown</option></select>
        <select aria-label="Urgency" value={urgency} onChange={(e) => setUrgency(e.target.value)}><option value="">Any urgency</option><option value="0">P0</option><option value="1">P1</option><option value="2">P2</option><option value="3">P3</option><option value="4">P4</option></select>
        <select aria-label="Verification" value={verification} onChange={(e) => setVerification(e.target.value)}><option value="">Any verification</option><option>unverified</option><option>eyewitness</option><option>corroborated</option><option>conflicting</option></select>
        <select aria-label="Assignment" value={assigned} onChange={(e) => setAssigned(e.target.value)}><option value="">Any assignment</option><option value="unassigned">Unassigned</option></select>
        <select aria-label="Sort" value={sort} onChange={(e) => setSort(e.target.value)}><option value="priority">Sort urgency</option><option value="age">Sort age</option></select>
      </div>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && rows.length === 0 && <Empty title="Inbox is empty" body="No stored reports match these filters. Zeros are not hidden incidents." />}
      {rows.length > 0 && (
        <div className="panel overflow-auto">
          <table>
            <thead><tr><th>State</th><th>Type</th><th>People</th><th>Verification</th><th>Age</th><th>Auth</th><th></th></tr></thead>
            <tbody>
              {rows.map((row) => (
                <tr key={row.id}>
                  <td><StateChip state={row.emergency_state} /></td>
                  <td>{row.incident_type}<div className="text-mute">{row.summary_text}</div></td>
                  <td>{row.people_count ?? "—"}</td>
                  <td>{row.verification_level}</td>
                  <td>{age(row.event_timestamp)}{stale(row.event_timestamp) ? " · stale" : ""}</td>
                  <td>{row.source_auth}</td>
                  <td><button className="btn ghost" onClick={() => setAckId(row.id)}>Mark seen</button></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      {ackId && (
        <Confirm
          title="Mark seen?"
          body="This records that an operator saw the report. It does not dispatch a team and it does not mean the person is safe."
          confirmLabel="Mark seen"
          onCancel={() => setAckId(null)}
          onConfirm={async () => {
            await api(`/api/v1/incidents/${encodeURIComponent(ackId)}/ack`, { method: "POST" });
            setAckId(null);
            reload();
          }}
        />
      )}
    </section>
  );
}

export function GroupsPage() {
  const { data, error, loading } = useApi<{ groups: { id: string; incident_type: string; confidence: string; source: string; members: unknown[]; assigned_team_id: string | null }[]; lineage: { id: string; event_type: string; group_id: string; details: string }[]; note: string }>("/api/v1/groups");
  return (
    <section>
      <h1 className="mt-0">Emergency groups</h1>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && <p className="text-mute">{data.note}</p>}
      {data && data.groups.length === 0 && <Empty title="No groups" body="Groups form only when conservative location rules match. Coarse GPS stays ungrouped." />}
      {data && data.groups.map((group) => (
        <article key={group.id} className="panel mb-3">
          <h2 className="mt-0">{group.incident_type} · {group.confidence} confidence · {group.source}</h2>
          <p>{group.members.length} reports. Assignment: {group.assigned_team_id ?? "none"}.</p>
        </article>
      ))}
      {data && data.lineage.length > 0 && (
        <div className="panel">
          <h2>Lineage</h2>
          <ul>{data.lineage.map((event) => <li key={event.id}>{event.event_type} · {event.group_id} · {event.details}</li>)}</ul>
        </div>
      )}
    </section>
  );
}

export function TeamsPage() {
  const { data, error, loading, reload } = useApi<{ teams: { id: string; name: string; status: string; availability: string; eta_note: string | null }[] }>("/api/v1/teams");
  const [name, setName] = useState("");
  return (
    <section>
      <h1 className="mt-0">Rescue teams</h1>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && data.teams.length === 0 && <Empty title="No teams" body="Create a team before assigning work. Civilians cannot appear here as authorities." />}
      <ul>{data?.teams.map((team) => <li key={team.id}>{team.name} · {team.status} · {team.availability} · ETA {team.eta_note ?? "unset"}</li>)}</ul>
      <form className="panel grid gap-2 max-w-md" onSubmit={async (e) => { e.preventDefault(); await api("/api/v1/teams", { method: "POST", body: JSON.stringify({ name, availability: "available" }) }); setName(""); reload(); }}>
        <label>New team<input value={name} onChange={(e) => setName(e.target.value)} required minLength={2} /></label>
        <button className="btn primary" type="submit">Create team</button>
      </form>
    </section>
  );
}

export function ConnectivityPage() {
  const { data, error, loading } = useApi<{ contacts: { kind: string; source_id: string; last_at: number; observations: number }[]; coverageClaim: null; note: string }>("/api/v1/connectivity");
  return (
    <section>
      <h1 className="mt-0">Connectivity</h1>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && <p className="text-hi">{data.note} Coverage claim: none.</p>}
      {data && data.contacts.length === 0 && <Empty title="No contacts observed" body="Gateway and peer observations will appear here after sync. Absence is not a coverage map." />}
      {data && data.contacts.length > 0 && (
        <table><thead><tr><th>Kind</th><th>Source</th><th>Last contact</th><th>Observations</th></tr></thead><tbody>
          {data.contacts.map((row) => <tr key={row.source_id + row.kind}><td>{row.kind}</td><td>{row.source_id}</td><td>{new Date(Number(row.last_at)).toISOString()}</td><td>{row.observations}</td></tr>)}
        </tbody></table>
      )}
    </section>
  );
}

export function UnknownPage() {
  const { data, error, loading } = useApi<{ zones: { lat_cell: number; lon_cell: number; last_contact: number; observations: number }[]; label: string; note: string }>("/api/v1/unknown-zones");
  return (
    <section>
      <h1 className="mt-0">Unknown zones</h1>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && <p>{data.label.replaceAll("_", " ")}. {data.note}</p>}
      {data && data.zones.length === 0 && <Empty title="No lost-contact cells" body="A cell appears only after a prior observation goes quiet for 30 minutes." />}
      <ul>{data?.zones.map((z) => <li key={`${z.lat_cell},${z.lon_cell}`}>{z.lat_cell}, {z.lon_cell} · last contact {new Date(Number(z.last_contact)).toISOString()} · {z.observations} observations</li>)}</ul>
    </section>
  );
}

export function AlertsPage() {
  const { data, error, loading, reload } = useApi<{ alerts: { id: string; title: string; kind: string; source_label: string; ai_generated: boolean; body: string }[]; officialFeed: { configured: boolean; reason: string } }>("/api/v1/alerts");
  const [form, setForm] = useState({ title: "", body: "", severity: "info", kind: "test", language: "en", confirmOfficial: "" });
  const [localError, setLocalError] = useState<string | null>(null);
  return (
    <section>
      <h1 className="mt-0">Alerts</h1>
      <ErrorNote error={error || localError} />
      {loading && <Skeleton />}
      {data && <p className="text-mute">Official feed: {data.officialFeed.reason}</p>}
      {data && data.alerts.length === 0 && <Empty title="No alerts" body="Nothing here is an official warning until a person publishes one with the required confirmation." />}
      <ul>{data?.alerts.map((alert) => <li key={alert.id}><span className={`chip ${alert.kind === "official" ? "official" : "test"}`}>{alert.source_label}</span> {alert.title} — AI generated: {String(alert.ai_generated)}</li>)}</ul>
      <form className="panel grid gap-2 max-w-xl" onSubmit={async (e) => {
        e.preventDefault();
        setLocalError(null);
        try {
          await api("/api/v1/alerts", { method: "POST", body: JSON.stringify(form) });
          reload();
        } catch (err) { setLocalError(err instanceof Error ? err.message : "failed"); }
      }}>
        <label>Title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label>
        <label>Body<textarea value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} required /></label>
        <label>Kind<select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value })}><option value="test">Test</option><option value="official">Official</option></select></label>
        <label>Language<select value={form.language} onChange={(e) => setForm({ ...form, language: e.target.value })}><option value="en">English</option><option value="hi">Hindi</option><option value="mr">Marathi</option></select></label>
        {form.kind === "official" && <label>Type VERIFIED_OFFICIAL_NOT_AI<input value={form.confirmOfficial} onChange={(e) => setForm({ ...form, confirmOfficial: e.target.value })} /></label>}
        <button className="btn primary" type="submit">Publish</button>
      </form>
    </section>
  );
}

export function ReviewPage() {
  const [text, setText] = useState("बाढ़ में चार लोग फंसे हैं");
  const [result, setResult] = useState<string>("");
  const [error, setError] = useState<string | null>(null);
  const hints = useApi<{ duplicates: unknown[]; contradictions: { note: string }[]; advisory: string }>("/api/v1/ai/suggest");
  return (
    <section>
      <h1 className="mt-0">AI-assisted review</h1>
      <p className="text-mute">Deterministic extractor. It cannot declare someone safe or publish an official warning.</p>
      <textarea aria-label="Source text" value={text} onChange={(e) => setText(e.target.value)} />
      <button className="btn primary mt-2" onClick={async () => {
        setError(null);
        try {
          const res = await api<unknown>("/api/v1/ai/extract", { method: "POST", body: JSON.stringify({ text }) });
          setResult(JSON.stringify(res, null, 2));
        } catch (err) { setError(err instanceof Error ? err.message : "failed"); }
      }}>Extract</button>
      <ErrorNote error={error || hints.error} />
      {result && <pre className="panel overflow-auto">{result}</pre>}
      {hints.data && <p>{hints.data.advisory} Contradictions: {hints.data.contradictions.length}. Duplicate hints: {hints.data.duplicates.length}.</p>}
    </section>
  );
}

export function TimelinePage() {
  const { data, error, loading } = useApi<{ events: { id: string; state: string; at_ms: number; detail: string }[]; packets: { message_id: string; accept_result: string; event_timestamp: number; received_at: number }[]; note: string }>("/api/v1/timeline");
  return (
    <section>
      <h1 className="mt-0">Packet timeline</h1>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && <p className="text-mute">{data.note}</p>}
      {data && data.events.length === 0 && <Empty title="No packet events" body="Queued, relayed, delivered, acknowledged, expired, and rejected events appear after sync." />}
      <ul>{data?.events.map((event) => <li key={event.id}>{event.state} · {new Date(Number(event.at_ms)).toISOString()} · {event.detail}</li>)}</ul>
    </section>
  );
}

export function AnalyticsPage() {
  const { data, error, loading } = useApi<{ byState: { emergency_state: string; n: number }[]; byType: { incident_type: string; n: number }[]; packets: { accept_result: string; n: number }[]; averageGatewayDelayMs: number | null; note: string }>("/api/v1/analytics");
  return (
    <section>
      <h1 className="mt-0">Analytics</h1>
      <ErrorNote error={error} />
      {loading && <Skeleton />}
      {data && <p className="text-mute">{data.note} Average gateway delay: {data.averageGatewayDelayMs == null ? "no accepted packets" : `${Math.round(data.averageGatewayDelayMs)} ms`}.</p>}
      {data && <Bars rows={[...data.byState.map((r) => ({ label: r.emergency_state, n: Number(r.n) })), ...data.packets.map((r) => ({ label: r.accept_result, n: Number(r.n) }))]} />}
    </section>
  );
}

export function SimulatorPage() {
  const { data, error, loading, reload } = useApi<{ scenarios: { id: string; description: string; nodes: number }[] }>("/api/v1/simulator/scenarios");
  const [output, setOutput] = useState<string>("");
  const [localError, setLocalError] = useState<string | null>(null);
  return (
    <section>
      <div className="panel mb-4" style={{ borderColor: "#f0c14b" }}>
        <strong>SIMULATOR — SEPARATE FROM LIVE DATA.</strong>
        <p>These runs use logical nodes. They are not phone-to-phone measurements and they do not enter the live dashboard.</p>
      </div>
      <ErrorNote error={error || localError} />
      {loading && <Skeleton />}
      <ul>
        {data?.scenarios.map((scenario) => (
          <li key={scenario.id} className="mb-2">
            <button className="btn ghost" onClick={async () => {
              setLocalError(null);
              try {
                const res = await api("/api/v1/simulator/run", { method: "POST", body: JSON.stringify({ scenario: scenario.id }) });
                setOutput(JSON.stringify(res, null, 2));
                reload();
              } catch (err) { setLocalError(err instanceof Error ? err.message : "failed"); }
            }}>{scenario.id}</button>
            <span className="text-mute"> {scenario.nodes} logical nodes. {scenario.description}</span>
          </li>
        ))}
      </ul>
      {output && <pre className="panel overflow-auto">{output}</pre>}
    </section>
  );
}

export function SettingsPage() {
  const me = useApi<{ user: { email: string; role: string; display_name: string } }>("/api/v1/auth/me");
  const users = useApi<{ users: { id: string; email: string; role: string; disabled: boolean }[] }>(me.data?.user.role === "admin" ? "/api/v1/users" : null);
  const audit = useApi<{ logs: { id: string; action: string; at_ms: number; detail: string }[] }>(me.data?.user.role === "admin" ? "/api/v1/audit" : null);
  const [confirm, setConfirm] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { /* role gate is server-side */ }, []);
  return (
    <section>
      <h1 className="mt-0">Settings</h1>
      <ErrorNote error={me.error} />
      {me.loading && <Skeleton />}
      {me.data && <p>Signed in as {me.data.user.email} · role {me.data.user.role}. Roles are enforced by the API, not by hiding buttons.</p>}
      {me.data?.user.role === "admin" && (
        <>
          <h2>Users</h2>
          <ul>{users.data?.users.map((user) => <li key={user.id}>{user.email} · {user.role} · {user.disabled ? "disabled" : "active"}</li>)}</ul>
          <h2>Audit log</h2>
          <ul>{audit.data?.logs.map((log) => <li key={log.id}>{new Date(Number(log.at_ms)).toISOString()} · {log.action} · {log.detail}</li>)}</ul>
          <button className="btn danger" onClick={() => setConfirm(true)}>Reset demo data</button>
          {message && <p>{message}</p>}
        </>
      )}
      {confirm && (
        <Confirm
          title="Delete demo operational data?"
          body="This deletes incidents, packets, groups, and alerts. Audit logs stay. Live need-help retention is a separate control."
          confirmLabel="Delete demo data"
          onCancel={() => setConfirm(false)}
          onConfirm={async () => {
            await api("/api/v1/admin/reset-demo", { method: "POST", headers: { "x-confirm-reset": "DELETE-DEMO-DATA" }, body: JSON.stringify({ confirm: "DELETE-DEMO-DATA" }) });
            setConfirm(false);
            setMessage("Demo data deleted. Audit retained.");
          }}
        />
      )}
    </section>
  );
}
